steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the Vite project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - VITE_SERVER_HOST=${_VITE_SERVER_HOST}

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_AR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}/IMAGE:$COMMIT_SHA', '.']

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}/IMAGE:$COMMIT_SHA']

  # Step 5: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--image', '${_AR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}/IMAGE:$COMMIT_SHA',
        '--platform', '${_PLATFORM}',
        '--region', '${_DEPLOY_REGION}',
        '--allow-unauthenticated'
      ]

images:
  - '${_AR_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}/IMAGE:$COMMIT_SHA'

# Define Cloud Run requirements
timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY